version: '3.1'

services:
  db:
    image: postgres
    volumes:
      - sql_data:/var/lib/postgres
    restart: always
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/my_secret
    ports:
      - 5432:5432
    secrets:
      - my_secret

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  sql_data: {}
secrets:
  my_secret:
    file: ./my_secret.txt